server:
	g++ util.cpp Epoll.cpp SockAddress.cpp Socket.cpp Host.cpp server.cpp -o server && \
	g++ util.cpp Epoll.cpp SockAddress.cpp Socket.cpp Host.cpp client.cpp -o client
clean:
	rm server && rm client